title: JohnPaul Kambazza
logo: /assets/img/logo.png
description: JPK's minimal is a theme for GitHub Pages.
show_downloads: false
guthub.is_project_page: false
google_analytics:
theme: jekyll-theme-minimal
